name: docker-pipeline
on: push

jobs:
  build-docker-file:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Prepare build environment  
    - run: go build -v ./... 
    - run: |
          for i in `seq 1 30`;
          do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for MySQL && exit 1
