name: docker-pipeline
on: push

jobs:
  build-docker-file:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Prepare Docker build   
      run: |
          docker build ./ECOMMERCE-API -t travel-web
